(function () {
  /* Generated by Tulip Inn Image Picker */

  const HERO    = "https://r1imghtlak.mmtcdn.com/03a63092-18c9-4020-98cd-784224e7b73d.jpg";
  const ABOUT   = "https://r1imghtlak.mmtcdn.com/1cd63876-be67-45a8-bad5-21a82fb66ff1.jpg";
  const GALLERY = [
    "https://r1imghtlak.mmtcdn.com/13c6b024-4db2-46a8-8da7-f3af0d17a4d5.jpg",
    "https://r1imghtlak.mmtcdn.com/11118c5d-296c-41cd-a098-07063b4ee652.jpg",
    "https://r1imghtlak.mmtcdn.com/3acd5771-beda-4404-9d89-ea31ee45e602.jpg",
    "https://r1imghtlak.mmtcdn.com/8cfe0d3a-5d80-4fa5-b5ce-34ae9141760f.jpg",
    "https://r1imghtlak.mmtcdn.com/c5ffe8a3-cf95-4b67-90f0-b1568ea67257.jpg"
  ];

  /* -- Hero background -- */
  if (HERO) {
    const heroBg = document.querySelector(".hero-bg");
    if (heroBg) {
      const cur = getComputedStyle(heroBg).backgroundImage;
      heroBg.style.backgroundImage = cur.includes("url(")
        ? cur.replace(/url\(['"]?[^'"\)\s]+['"]?\)\s*$/, `url('${HERO}')`)
        : `url('${HERO}')`;
    }
  }

  /* -- About photo -- */
  if (ABOUT) {
    const aboutImg = document.querySelector(".about-img");
    if (aboutImg) aboutImg.src = ABOUT;
  }

  /* -- Gallery images -- */
  const galImgs = document.querySelectorAll(".gallery-grid .gal-img");
  GALLERY.forEach(function (url, i) {
    if (url && galImgs[i]) galImgs[i].src = url;
  });

})();
